base_url = "https://gutenberg-editorial-simple.netlify.com/"
compile_sass = true
title = "Editorial theme"
description = "A clean blogging theme"

[extra]
editorial_sticky = true
editorial_reverse = false
editorial_theme = ""
editorial_links = [
    {url = "https://google.com", name = "About"},
]
