name = "editorial"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/zoosky/gutenberg-hyde"
min_version = "0.4"
demo = "https://gutenberg-editorial-simple.netlify.com"

[extra]
editorial_sticky = true
editorial_reverse = false
editorial_theme = ""
editorial_links = [
]

[author]
name = "Andreas Kapp"
homepage = "https://kapp.technology"

[original]
author =  "ajlkn"
homepage = "https://html5up.net/editorial"
repo = ""
